# Generated by Django 2.1 on 2018-10-01 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_number', models.IntegerField(default=website.models.get_acc_num)),
                ('balance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('authorize_review', 'Authorize review of Transactions'), ('initiate_info_mod', 'Initiate information modification'), ('view_transaction', 'View transaction details')),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('delete_transaction', 'Delete a transaction'),),
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_rel_man', to='website.Employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_merchant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('authorize_review', 'Authorize review of Transactions'), ('initiate_info_mod', 'Initiate information modification'), ('view_transaction', 'View transaction details')),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='NONE', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='NONE', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('add_transaction', 'Create a New Transaction'),),
            },
        ),
        migrations.CreateModel(
            name='ProfileModificationReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='NONE', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='NONE', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sys_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('auth_crit_trans', 'Authorize Critical Transaction'),),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('isValidated', models.BooleanField(default=False)),
                ('recipientAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='website.Account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('senderAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_account', to='website.Account')),
                ('signator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signator', to='website.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='customerindividual',
            name='relationship_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indi_customer_rel_man', to='website.Employee'),
        ),
        migrations.AddField(
            model_name='customerindividual',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_indi_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Profile'),
        ),
    ]
