# Generated by Django 2.1 on 2018-10-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='isValidated',
            new_name='is_validated',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='recipientAccount',
            new_name='recipient_account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='senderAccount',
            new_name='sender_account',
        ),
    ]
