# Generated by Django 2.1 on 2018-10-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181009_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_validated',
            field=models.IntegerField(default=0),
        ),
    ]
