# Generated by Django 2.1 on 2018-10-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20181023_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerindividual',
            name='otp_secret',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='merchant',
            name='otp_secret',
            field=models.CharField(default='', max_length=16),
        ),
    ]
