# Generated by Django 2.0 on 2018-08-25 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180824_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='account',
            name='accNumber',
            field=models.IntegerField(default=website.models.getAccNum),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='signator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='signator', to=settings.AUTH_USER_MODEL),
        ),
    ]
