# Generated by Django 2.1 on 2018-09-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180825_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='isCritical',
        ),
    ]
