# Generated by Django 2.1 on 2018-09-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_transaction_iscritical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='signator',
        ),
    ]
