# Generated by Django 2.1 on 2018-10-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20181024_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aadhar_number',
            field=models.CharField(default='NONE', max_length=15),
        ),
        migrations.AddField(
            model_name='profilemodificationreq',
            name='aadhar_number',
            field=models.CharField(default='NONE', max_length=15),
        ),
    ]
