# Generated by Django 2.1 on 2018-10-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20181024_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_mode',
            field=models.CharField(default='debit', max_length=20),
        ),
    ]
