# Generated by Django 2.1 on 2018-10-30 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0009_auto_20181030_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sys_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('auth_crit_trans', 'Authorize Critical Transaction'), ('verify_profile_requests', "Verify Users' Profile Updation Requests"), ('internal_user_account_management', "Add/Modify/Delete Internal User's Account"), ('external_user_account_management', "Add/Modify/Delete External User's Account upon Request"), ('access_sys_log', 'Access System Logs'), ('access_pii', 'Access PII after authorization from Govt. No Direct Access')),
            },
        ),
    ]
