# Generated by Django 2.1 on 2018-10-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20181030_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='public_key',
            field=models.CharField(default='NONE', max_length=1000000),
        ),
    ]
