# Generated by Django 2.1 on 2018-10-31 23:19

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_profile_public_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='public_key',
        ),
        migrations.AddField(
            model_name='profile',
            name='private_key',
            field=models.CharField(default=website.models.generate_private_key, max_length=1000000),
        ),
    ]
